version: "3.9"
services:
  zigbee-prometheus-exporter:
    container_name: zigbee-prometheus-exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config:/core/config/
    env_file:
      - config.env
