version: "3.9"
services:
  zigbee-prometheus-exporter:
    container_name: zigbee-prometheus-exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config/device-config.json:/core/device-config.json
      - ./config/last-state.json:/core/state/last-state.json
    env_file:
      - config.env
